const MusiciansAPIen = {
  musisians: [
    { number: 1, name: "Slava KPSS", fileName: "Slava_KPSS"},
    { number: 2, name: "Scally Milano", fileName: "Scally_milano"},
    { number: 3, name: "Kizyaka", fileName: "Kizyaka"},
    { number: 4, name: "Krovostok", fileName: "Krovostok"},
    { number: 5, name: "Soloduha", fileName: "Soloduha"},
    { number: 6, name: "Kunteynir", fileName: "Kunteynir"}
  ],
  Data: [
    {number: 1, birthYear: "1990",deathYear: "н.в.",birthDate: "09.05.1990",deathDate: "present",
    shortInfo:"Vyacheslav Valeryevich Mashnov (born May 9, 1990, Khabarovsk, USSR), better known by the pseudonym Slava KPSS, is a Russian rap artist, poet, participant in rap battles, as well as an artist and streamer.",
    events: [
      {year:"2017",description:"Slava KPSS «Tea for Two» with Aux\nSlava KPSS «Sun of the Dead»"},
      {year:"2018",description:"Slava KPSS 'Adult Dance Music',\nSlava KPSS 'OVERHYPE' with Khan Zamai,\nSlava KPSS 'OVERHYPE 2' with Khan Zamai,\nSlava KPSS 'OVERHYPE 3' with Khan Zamai"},
      { year: "2019", description: "Slava KPSS 'Buter Brodsky'" },
      { year: "2020", description: "Slava KPSS 'Monster that Ruined the World'" },
      { year: "2021", description: "Slava KPSS 'Lil Buter'" },
      { year: "2022", description: "Slava KPSS 'Buter Brodsky 2'" },
      { year: "2023", description: "Slava KPSS 'GORGOROD 2',\n(a sequel to Oxxxymiron's album 'GORGOROD')" }],
    quote: "Our fixies died\nBefore they used to move something\nInside the souls, now ink flows\nAnd who will plug the hole in the meaty house?\nWalkers rose, time is standing\nIn a quiet backwater, demons draw for me\nYou pour lead on bare nerves",
    quoteAuthor: "Slava KPSS in the song 'Guaranteed Guys'",  
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"], 
    Namealbums : ["Camp Dust", "ANTIHYPETRAIN", "Lil Buter", "Favorite Songs of Real People", "Gorgorod 2", "Adult Dance Music"],
    videoLink: "https://www.youtube.com/embed/LYoNRVZG6W0?si=FuuBclg-L5ORSKp0",
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1999.4094895361554!2d30.3618821!3d59.925347099999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNTnCsDU1JzMxLjMiTiAzMMKwMjEnNDIuOCJF!5e0!3m2!1sru!2sby!4v1702552085999!5m2!1sru!2sby",
  },

    {number: 2, birthYear: "2002",deathYear: "н.в.",birthDate: "25.03.2002",deathDate: "present",
    shortInfo:"(born March 25, 2002, Berezniki, Perm Krai), better known as Scally Milano, is a Russian rapper. He attracted public attention with his provocative style and music addressing controversial topics. Scally Milano's music is often described as a mix of absurdity and provocation.",
    events: [
      { year: "May 18, 2021", description: "Mini-album 'Onion'" },
      { year: "December 17, 2021", description: "Album 'Money Counter Music'" },
      { year: "May 6, 2022", description: "Album 'Propaganda of Money'" },
      { year: "December 16, 2022", description: "Album 'Really Rich'" }],
    quote: "Bro says, be popular and do TikToks\nActually, TikToks\nOn my phone tracker, I know when the cops are nearby\nSome guy says, I'm his brother - dude, who are you?\nGive me a counter, can't count the banknotes",
    quoteAuthor: "Scally Milano",
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg"], 
    Namealbums : ["Onion", "Money Counter Music", "Propaganda of Money", "Really Rich"], 
    videoLink: 'https://www.youtube.com/embed/8zRa_CsrmDY?si=KVQlIaOAEK6encMI',
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d2245.3722005272784!2d37.6161743!3d55.7520363!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNTXCsDQ1JzA3LjMiTiAzN8KwMzYnNTguMiJF!5e0!3m2!1sru!2sby!4v1702551831923!5m2!1sru!2sby" },

    {number: 3, birthYear: "1989",deathYear: "н.в.",birthDate: "21.05.1989",deathDate: "present",
    shortInfo:"Oleg Viktorovich Nechiporenko (born May 21, 1989, Leningrad, RSFSR, USSR), better known by the stage name Kizyaka (stylized in lowercase), is a Russian hip-hop artist. He is a member and founder of the creative association 'Haunted Family.' Kizyaka is an uncompromising new wave rap artist residing in Barcelona. He raps in the 'trap' subgenre, dedicating his compositions to everything that is usually shielded from youth. He is the first and only Russian rapper listed in Interpol.",
    events: [
      { year: "October 12, 2016", description: "Album 'Mas Fuerte'" },
      { year: "August 15, 2019", description: "Album 'Karmageddon'" },
      { year: "October 22, 2021", description: "Album 'BANDANA'" },
      { year: "July 28, 2023", description: "Mini-album 'Gremlin'" }],
    quote: "Dude, why do you need a chain? Buy yourself a brain.",
    quoteAuthor: "Kizyaka",
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg"],
    Namealbums : ["Mas Fuerte","Karmageddon","BANDANA","Gremlin"], 
    videoLink: "https://www.youtube.com/embed/z7SkNWQINds?si=7IfuYPb3D1q2MzjI",
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d2993.4310511417484!2d2.1683972759183243!3d41.3864443713!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNDHCsDIzJzExLjIiTiAywrAxMCcxNS41IkU!5e0!3m2!1sru!2sby!4v1702552217509!5m2!1sru!2sby",
  },

{number: 4, birthYear: "1961",deathYear: "2022",birthDate: "29.09.1971",deathDate: "present",
shortInfo:"Krovostok is a Russian hip-hop group from Moscow, founded in 2003 by artists Anton Chernyak and Dmitry Fain. The group is known primarily for satirical songs from the perspective of a lyrical character with exaggerated, grotesque criminal themes, delivered in a monotone recitative. The lyrics are written by Dmitry Fain and Anton Chernyak, and the music is composed by Phantom, DJ Polutrup.",
    events: [
      { year: "2004", description: "Album 'River of Blood'" },
        { year: "2006", description: "Album 'Through'" },
        { year: "2008", description: "Album 'Gantelya'" },
        { year: "2012", description: "Album 'Studen'" },
        { year: "2015", description: "Album 'Lombard'" },
        { year: "2018", description: "Album 'ChB'" },
        { year: "2021", description: "Album 'Science'" }],
    quote: "Moral restrictions are always needed for a person; they are like fire extinguishers, and this is not nonsense.",
    quoteAuthor: "Anton Chernyak of the group 'Krovostok'",      
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg"],
    Namealbums :["River of Blood", "Through", "Gantelya", "Studen", "Lombard", "ChB", "Science"],
    videoLink: "https://www.youtube.com/embed/wNOUlTNHPMM?si=1CfAPk9EZM6SrgSv" ,
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d2247.443885415185!2d37.7275326!3d55.716037699999994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNTXCsDQyJzU3LjciTiAzN8KwNDMnMzkuMSJF!5e0!3m2!1sru!2sby!4v1702552322810!5m2!1sru!2sby"
  },

{number: 5, birthYear: "1959",deathYear: "н.в.",birthDate: "18.01.1959",deathDate: "present",
shortInfo:"Alexander Antonovich Solodukha (born January 18, 1959, Kamenka, Sergiev Posad District, Moscow Region, RSFSR, USSR) is a Soviet and Belarusian singer. He is an Honored Artist of the Republic of Belarus (2018). Solodukha worked as a doctor and participated in amateur artistic activities.",
    events: [
      { year: "1987", description: "Since 1987 — soloist of the State Concert\nOrchestra of Belarus." },
        { year: "1989", description: "Began working as a soloist for the song\ntheater of Yadviga Poplavskaya — Alexander Tikhonovich." },
        { year: "1995", description: "Album 'Hello, Stranger'" },
        { year: "2004", description: "Winner of 'Song of the Year of Ukraine 2004'\n(with the song 'Hello, Stranger')." },
        { year: "2009", description: "Album 'Only 50'" },
        { year: "2015", description: "Album 'The Best for 15 Years'" },
        { year: "2017", description: "Album 'We Will Be Together'" },
        { year: "2019", description: "Album 'New and Best'" },
        { year: "2020", description: "Album 'Young Boys'" }],
    quote: "Young guys: one guitar for three. With picking and striking, songs of summer and spring...",
    quoteAuthor: "Sanya Solodukha",
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"], 
    Namealbums : ["Hello, Stranger", "Only 50", "The Best for 15 Years", "We Will Be Together", "New and Best", "Young Boys"], 
    videoLink: "https://www.youtube.com/embed/1I4VsgMb-GI?si=XIBJxm94thyr3eGP" ,
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d2351.046063801322!2d27.560312899999996!3d53.8953852!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNTPCsDUzJzQzLjQiTiAyN8KwMzMnMzcuMSJF!5e0!3m2!1sru!2sby!4v1702552481446!5m2!1sru!2sby",
  },
  {number: 6, birthYear: "1984",deathYear: "н.в.",birthDate: "01.07.1984",deathDate: "present",
shortInfo:"Kunteynir (Russian: Контейнер) is a Russian hip-hop group from Moscow, formed in 2001. From 2009 to 2013, the group suspended its activities due to the arrest and subsequent imprisonment of the leader, Pasha Tekhnik. In 2016, the collective disbanded. In 2020, MC Kalmar and Pasha Tekhnik reunited the group and recorded the album 'Road to the Clouds.' Critics have defined the group's work as underground rap, alternative hip-hop, and avant-garde rap. ",
    events: [
      { year: "2004", description: "Album 'Edward Scissorhands Paper'" },
      { year: "2007", description: "Album 'Blewburger'" },
      { year: "2013", description: "Album '5 Years'" },
      { year: "2014", description: "Album 'Foundation'" },
      { year: "2020", description: "Album 'Road to the Clouds'" }],
    quote: "If there's not enough for OG Buda, \nthen we chop it with the boys. \nOn beats from Chernogolovka, \nfrom the windows of Rublyovka. \nYou smile less and frown more. \nHere they thrive on those who barely make it.",
    quoteAuthor: "OG Kunteynir",
    albums : ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg"],
    Namealbums : ["Edward Scissorhands Paper", "Blewburger", "5 Years", "Foundation", "Road to the Clouds"], 
    videoLink: "https://www.youtube.com/embed/7YzCKxL1Luw?si=mA9i4fByECF5rpPV" ,
    maplink: "https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d2475.1883229377486!2d39.17972989999999!3d51.656388299999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNTHCsDM5JzIzLjAiTiAzOcKwMTAnNDcuMCJF!5e0!3m2!1sru!2sby!4v1702552563317!5m2!1sru!2sby",
  },

  ],
  all: function() { return this.musisians},
}
export default MusiciansAPIen;
